# SQLite version 3.x
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/lbbs_db_development.sqlite3

test:
  <<: *default
  database: db/lbbs_db_test.sqlite3

# production:
#   <<: *default
#   database: db/lbbs_db_production.sqlite3
production:
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: ENV['LBBS_DB_PRODUCTION_PASSWORD'].present?
  pool: 5
  database: lbbs_db_production